spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx339336302995faa2
  mpAppSecret: e0a139c7e3e617763810e6708b7d0d9c
  mchId: 123
  mchKey: kk
  keyPath: /home
  notifyUrl: http://127.0.0.1:8080/sell/pay/notify
  openAppId: 123
  openAppSecret: kk

projecturl:
  weChatMpAuthorize:
  weChatOpenAuthorize:
  sell: